<HomeScreen>:
    name: "home_screen"

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        GridLayout:
            size_hint: (1.00, 0.85)
            rows: 2
            cols: 1
        
            Label:
                index: 0
                text: "Home Screen"
            RegionInput:

        ScreenNavigationBar:
            size_hint: (1.00, 0.15)


<RegionInput>:
    Label:
        text: "Enter a region"